all: loi.pdf

loi.pdf: loi.tex coreTeam.tex vision.tex approach.tex usApplicants.tex resources.tex figures/focusAreas.tex figures/dataAnalysisBehavior.tex figures/dataAnalysisNeural.tex figures/figArena.tex
	pdflatex loi.tex
